### ISSUE TITLE
Keyboard navigation not working after opening image

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-expandable-image-gallery-changelog#1]
Hi Team, 

After opening an image from the image gallery (https://codyhouse.co/ds/components/app/expandable-image-gallery--morphing-images), the keyboard navigation is not working as the focus goes immediately to the 'share button' in the menu bar. Only after clicking anywhere else in the lightbox (and the focus disappears), the keyboard navigation is working. Can you please look into this?

Regards,
Yannick

**Comment by claudia-romano** [comment]
Hi Yannick,
the focus moves to the first focusable element. This is the default behaviour of the modal component that we use to create the image gallery.

We have just pushed an update to the modal component that gives you the option to pass the element you want to pass the focus to. Please make sure to update the javascript of the modal component. You can get the code here:
https://codyhouse.co/ds/components/app/modal-window

And then, in the HTML of your image gallery, add the ```data-modal-first-focus=".js-exp-lightbox__body"``` to the ```.js-exp-lightbox element```:
```
<div id="expLightbox" class="modal exp-lightbox bg js-modal js-exp-lightbox" data-animation="on" data-modal-first-focus=".js-exp-lightbox__body">
  <!-- other content here -->
</div>
```
That should fix your issue. Cheers

**Comment by YannickMol** [comment]
Hi Claudia, 

This has indeed fixed my issue, thanks!

Regards,
Yannick
