### ISSUE TITLE
Errors when only a single item in the gallery

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-expandable-image-gallery-changelog#2]
I just noticed some errors occurring when only a single gallery item is present in the slideshow. The issue occurred on line 134 and 143 where you have an if statement:
`if(gallery.slideshowObj.options.swipe) {`

The `gallery.slideshow` is undefined when only one gallery item exists.

I changed the code to `if(gallery.slideshowObj && gallery.slideshowObj.options.swipe) {` on line 134 and `if(gallery.zoomImg && gallery.slideshowObj && gallery.slideshowObj.options.swipe) {` on line 143 to make it work on my project. 

Hope this helps.

Dominic

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. 
We just pushed an update that should fix that issue. 

Cheers,

**Comment by dominicht** [comment]
Awesome. Thanks!
