### ISSUE TITLE
Different image in modal not working

### ISSUE THREAD

**Issue by YannickMol** [CodyHouse/cd-expandable-image-gallery-changelog#3]
Hi Team,

You mention the following on the info page of the component:

> Add a data-src attribute to the <img> element inside the .js-exp-gallery equal to the src of the image you want to show in the modal;

I tried to set two different image sizes in html, but somehow it is automatically updating the src to the same value as data-src, once accessed through a browser. See screenshot below.

![image](https://user-images.githubusercontent.com/13256289/81509453-1b4a5100-930b-11ea-9f25-9aaf6feca71b.png)

Is this something that can be fixed?

Thanks,
Yannick

**Comment by claudia-romano** [comment]
Hi Yannick,
thanks for the heads up. There was a conflict between the Expandable Image Gallery and the Lazy Load component that you are using for the image gallery items (they both used the data-src attribute). 

We modified the Expandable Gallery component to use a different data attribute (data-modal-src) to avoid that conflict. You can find more info here:
https://codyhouse.co/ds/components/info/expandable-image-gallery#gallery

You can get the updated JS code from the component demo page:
https://codyhouse.co/ds/components/app/expandable-image-gallery

This should fix the problem. Please feel free to reopen this issue you are still experiencing it. Cheers.
