### ISSUE TITLE
Close the modal window clicking outside the expanded picture

### ISSUE THREAD

**Issue by retroriff** [CodyHouse/cd-expandable-image-gallery-changelog#4]
Hello, a great feature for desktop devices would be to close the modal window when the user clicks on the js-modal outside of the expanded picture.

**Comment by claudia-romano** [comment]
Hi there, thanks for the suggestion. The component has been updated to include this new feature.
You can get the updated JS code here:
https://codyhouse.co/ds/components/app/expandable-image-gallery

The HTML of the component has been updated as well to include the `.pointer-events-none/.pointer-events-auto` classes. Cheers!
