### ISSUE TITLE
Expandable Image Gallery + Filterable Product Gallery

### ISSUE THREAD

**Issue by vibe9** [CodyHouse/cd-expandable-image-gallery-changelog#5]
I want to combine the following two components: Expandable Image Gallery + Filterable Product Gallery, so that once you have filtered a group of items if you open the Lightbox gallery then only the items that are filtered will show up in that gallery.

Thinking about this further, it would also make sense to extend the functionality of the gallery to be able to have the ability to have galleries determined by a data attribute such as data-category. 

An example would be a catalogue of portfolio pieces set in a grid of thumbnail images, where you feature 4 images for each among a list of say 20 projects. You then want the ability to have a user click on any thumbnail within a group of 4 and view a gallery of only those 4 images, based on the data-category="projectName".

**Comment by claudia-romano** [comment]
Hi there,
the component has been updated to be used in combo with the Filterable Product Gallery component. You would need to update both the Expandable Image Gallery and the Slideshow components JS code:
https://codyhouse.co/ds/components/app/expandable-image-gallery
https://codyhouse.co/ds/components/app/slideshow

About the data-category option: when clicking on one of the images, the user expects to have access to all the visible images in the gallery, not only to a subsection. 
It may not be clear to the user why clicking one image triggers a modal with some images while clicking another image triggers a different modal of images. For this reason, we have decided not to include this feature for now.

I'm going to close this issue, but if you have any other thoughts you want to share, feel free to reopen it. Cheers!

**Comment by vibe9** [comment]
Amazing thanks so much! The only other component I would love this to be combined with is the Infinite Scroll / Load More button.
